FORMAT: 1A
HOST: http://cerc-api-staging.herokuapp.com/

# CERC API - Financiador

A "CERC API - Financiador" é uma plataforma que oferece aos Agentes Financiadores habilitados junto à CERC um conjunto de serviços voltados para operações com recebíveis. Esses serviços compreendem o fornecimento de informações sobre os recebíveis, sobre os documentos fiscais a estes relacionados e sobre seus participantes.
Estão disponíveis ainda serviços de consulta de informações sobre os recebíveis registrados na CERC associados ao Agente Financiador, inclusive o monitoramento da carteira.

## Formato da resposta

Para obter o formato da resposta da API em um determinado formato (XML ou JSON), deve ser colocado o formato ao final do `path`, da seguinte forma:

Por exemplo:

  - Para obter os dados em `json` do `/path/to/resource` ficaria `/path/to/resource.json`.
  - Para obter os dados em `xml` do `/path/to/resource?params=1231` ficaria `/path/to/resource.xml?params=1231`.

Os formatos válidos no momento são `json` e `xml`.

## Autenticação

Para utilizar a API, é necessário enviar o `token` de acesso em toda requisição. Antes de fazer qualquer requisição para os endpoints documentados, consulte a sessão de autenticação para saber como obter o `token` de autenticação.

## Campo `type`

Para envio de dados por xml, é importante que os atributos de `type` estejam presentes com os valores corretos. Ou seja, para indicar que um campo é `integer`, deve se adicionar o atributo `type="integer"`. O mesmo vale para campos do tipo `array` e `time`. Para os valores `string`, o atributo `type` é opcional e não precisa ser adicionado.

## Múltiplos parâmetros em `query string`

Em requisições com método `GET`, todos os parâmetros devem ser passados pela `query string`. Em caso de parâmetros que aceitem mais de um valor, ou seja, parâmetros que são `arrays`, elas devem ser enviadas no seguinte formato: `params[]=35&params[]=47&params[]=12`, que equivale a `params = [35, 47, 12]`.

## Autenticação [/v1/authentication]

A maioria dos endpoints documentados requer que as requisições venham com o `token` de acesso no campo `Authorization` do `Headers` da requisição. Ou seja:

`Authorization: Bearer {access-token}`

Para obter o `token` de acesso, consulta o endpoint de `Autenticação de usuário de agente`.

### Autenticação de usuário de agente [GET]

+ Attributes

    + cpf (string) - CPF do usuário de agente registrado no sistema. Deve estar com máscara no formato: `XXX.XXX.XXX-XX`.
    + password (string) - Senha de acesso do usuário de agente associado ao CPF.
    + type (string) - Tipo de usuário que deseja se autenticar. Para autenticação de usuário de agente, enviar o valor `agent_user`

+ Request (application/xml)

        <?xml version="1.0" encoding="UTF-8"?>
        <request>
          <cpf>073.008.792-17</cpf>
          <password>123123123</password>
          <type>agent_user</type>
        </request>

+ Response 200 (application/xml)

    + Attributes(Response Base)

        + `access-token` (string) - `Token` de autenticação que deve ser enviado nas requisições para os outros endpoints.
        + `user` (Agent User)

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <response>
              <code type="integer">200</code>
              <description>Sucesso</description>
              <access-token>57b77bd24f707366173a76e0</access-token>
              <user>
                <name>Luiz Paulo</name>
                <email>luiz.paulo@gmail.com</email>
                <telephone-number>(11) 12345-1234</telephone-number>
              </user>
            </response>


+ Response 422 (application/xml)

    Caso o CPF não exista e/ou a senha não está de acordo com o CPF.

    + Attributes(Response Base)

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <response>
              <code type="integer">422</code>
              <description>Combinação de CPF e senha inválidos.</description>
            </response>

## Validação de NF-e em lote [/v1/nfe-validations]

Conjunto de serviços que compreende a busca dos dados das notas fiscais de um lote e de dados de seus participantes. O conjunto de informações compreende os dados disponibilizados pelo serviço de consulta de notas fiscais eletrônicas das Secretarias de Fazenda Estaduais e pelo serviço de consulta de CNPJ da Receita Federal.
Sobre os dados encontrados nessas fontes, são aplicados algoritmos para verificar a elegibilidade dos recebíveis para uso como lastro de operações bancárias ou de securitização de direitos creditórios.
Os dados obtidos a partir de cada consulta são armazenados por um determinado período e são fornecidos a partir do acionamento combinado dos serviços descritos abaixo.

### Solicitação de validação de NF-e em lote [POST]

+ Attributes

    + `agent-id` (string) - Identificador do agente financiador ao qual será associada a validação.
    + `nfe-keys` (array[string]) - Lista de chaves de nota fiscais que se deseja validar. Cada chave de nota fiscal deve estar com máscara no formato: `"**** **** **** **** **** **** **** **** **** **** ****"`

+ Request (application/xml)

    + Headers

            Authorization: Bearer {token}

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <request>
              <agent-id>5791101d4f707323fc55ef89</agent-id>
              <nfe-keys type="array">
                <nfe-key>2616 0171 7587 1745 7358 8901 0461 0113 2569 8211 1855</nfe-key>
                <nfe-key>1116 0162 3738 5963 8289 1490 9020 8969 3578 3754 2665</nfe-key>
                <nfe-key>2316 0107 1775 6653 0603 3711 4166 4524 5887 8982 0029</nfe-key>
                <nfe-key>5316 0100 2346 2004 2270 0882 6906 4379 5156 7844 8973</nfe-key>
                <nfe-key>2416 0199 5643 8207 8924 4703 4983 7491 0132 1153 2500</nfe-key>
              </nfe-keys>
            </request>

+ Response 202 (application/xml)
    Em caso de sucesso

    + Attributes(Response Base)

        + `batch-id` (string) - Identificador do lote de validação de notas fiscais.

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <response>
              <code type="integer">202</code>
              <description>O lote foi aceito e será processado.</description>
              <batch-id>57b77bd24f707366173a76e0</batch-id>
            </response>


+ Response 400 (application/xml)

+ Response 422 (application/xml)

    Parâmetros inválidos.

    + Attributes(Response Base)

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <response>
              <code type="integer">422</code>
              <description>Parâmetros inválidos.</description>
              <errors type="array">
                <error>agent_id não pode estar em branco</error>
              </errors>
            </response>

### Consulta de status das validações de NF-e [GET /v1/nfe-validations{?agent_id,batch_ids,status,created_since,created_until,completed_since,completed_until,per_page,page}]

+ Request

    + Headers

            Authorization: Bearer {token}

+ Parameters

    + agent_id (optional)
        Identificadores do agente financiador registrado no momento da criação de validação de nota fiscal.

    + `batch_ids` (optional)
        Identificadores dos lotes de validação de nota fiscal. Aceita múltiplos valores na forma: `?batch_ids[]=35&batch_ids[]=47&batch_ids[]=12`

    + status (optional)
        Filtra as validações pelo campo `status`. Sem esse valor, as validações retornadas podem ter qualquer `status`.
        + Members
            + `pendente`
            + `processando`
            + `concluido`
            + `com_erro`

    + created_since (optional)
        Tempo no formato iso8601, retorna todas as validações criadas desde o momento especificado. Por padrão o valor é o início do dia que foi feita a requisição.

    + created_until (optional)
        Tempo no formato iso8601, retorna todas as validações criadas até o momento especificado. Por padrão o valor é o momento corrente da requisição.

    + completed_since (optional)
        Tempo no formato iso8601, retorna todas as validações completadas desde o momento especificado. Por padrão o valor é o início do dia que foi feita a requisição.

    + completed_until (optional)
        Tempo no formato iso8601, retorna todas as validações completadas até o momento especificado. Por padrão o valor é o momento corrente da requisição.

    + per_page (optional, number)
        Número máximo de registros que devem ser retornados por página. Deve ser um inteiro de `1` a `1000`.
        + Default: `1000`

    + page (optional, number)
        Número da página que deve ser retornada. Deve ser um inteiro começando em `1`.
        + Default: `1`

+ Response 200 (application/xml)

    Em caso de sucesso, será retornado uma lista com as validações de nota fiscal filtradas pelos parâmetros.

    O campo `id` da validação só será adicionado quando o status da validação for `Concluido com sucesso`.

    + Attributes(Response Base)

        + `nfe-validations` (array[NfeValidation]) - Lista de validações de nota fiscal.

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <response>
              <code type="integer">200</code>
              <description>Sucesso</description>
              <nfe-validations type="array">
                <nfe-validation>
                  <status>pendente</status>
                  <agent-id>57b7876a4f707366173a76e1</agent-id>
                  <nfe-key>5316 0100 2346 2004 2270 0882 6906 4379 5156 7844 8973</nfe-key>
                  <created-date type="time">2016-08-19T13:27:53-03:00</created-date>
                  <batch-id>57bf40534f70730471178b02</batch-id>
                </nfe-validation>
                <nfe-validation>
                  <id>57ab9abb4f707364d6c251ca</id>
                  <status>concluido</status>
                  <agent-id>57b7876a4f707366173a76e1</agent-id>
                  <nfe-key>5316 0100 2346 2004 2270 0882 6906 4379 5156 7844 8973</nfe-key>
                  <created-date type="time">2016-08-19T13:27:53-03:00</created-date>
                  <completed-date type="time">2016-08-19T13:27:53-03:00</completed-date>
                  <batch-id>57bf40534f70730471178b02</batch-id>
                </nfe-validation>
                <nfe-validation>
                  <status>com_erro</status>
                  <agent-id>57b7876a4f707366173a76e1</agent-id>
                  <nfe-key>53168973</nfe-key>
                  <created-date type="time">2016-08-19T13:27:53-03:00</created-date>
                  <errors type="array">
                    <error>Chave de nota fiscal inválida</error>
                    <error>Chave de nota fiscal com máscara inválida</error>
                  </errors>
                  <batch-id>57bf40534f70730471178b02</batch-id>
                </nfe-validation>
              </nfe-validations>
            </response>

### Consulta de dados da NF-e [GET /v1/nfe-validations/{nfe_validation_id}/nfe]

+ Request

    + Headers

            Authorization: Bearer {token}

+ Parameters

    + nfe_validation_id - Identificador da validação de nota fiscal.

+ Response 200 (application/xml)
    NFe pertencente a validação de nota fiscal.

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <response>
              <code type="integer">200</code>
              <description>Sucesso</description>
              <nfe>
                <chave-acesso>12-3456-78.909.876/5432-10-12-345-678.909.876-543.210.123-4</chave-acesso>
                <cobranca>
                    <fatura>
                        <numero>000000</numero>
                        <valor-original>10.000,10</valor-original>
                        <valor-desconto>0,10</valor-desconto>
                        <valor-liquido>10.000,00</valor-liquido>
                        <normalizado-valor-original>10000.1</normalizado-valor-original>
                        <normalizado-valor-desconto>0.1</normalizado-valor-desconto>
                        <normalizado-valor-liquido>10000</normalizado-valor-liquido>
                    </fatura>
                    <duplicatas>
                        <duplicata>
                            <numero>123456-78</numero>
                            <vencimento>01/12/2016</vencimento>
                            <valor>5.000,00</valor>
                            <normalizado-valor>5000</normalizado-valor>
                        </duplicata>
                    </duplicatas>
                </cobranca>
                <destinatario>
                    <nome>EMPRESA FANTASIA LTDA.</nome>
                    <cnpj>01.234.567/8901-23</cnpj>
                    <cpf />
                    <endereco>AVENIDA COMERCIAL, 201</endereco>
                    <bairro>PRACA CENTRAL</bairro>
                    <cep>01234-567</cep>
                    <municipio>0000000 - AGUAS BRANCAS</municipio>
                    <telefone>(01)98765-4321</telefone>
                    <uf>AC</uf>
                    <pais>1058 - BRASIL</pais>
                    <indicador-ie>01 - Contribuinte ICMS</indicador-ie>
                    <ie>123456789</ie>
                    <suframa />
                    <im />
                    <email>comercial@fantasia.com.br</email>
                    <normalizado-cnpj>01234567890123</normalizado-cnpj>
                    <normalizado-cpf />
                    <normalizado-cep>01234567</normalizado-cep>
                    <normalizado-municipio>0000000</normalizado-municipio>
                    <normalizado-pais>1058</normalizado-pais>
                    <normalizado-indicador-ie>1</normalizado-indicador-ie>
                </destinatario>
                <emitente>
                    <nome>COMERCIO DE OBJETOS LTDA.</nome>
                    <nome-fantasia>OBJETOCOM</nome-fantasia>
                    <cnpj>32.109.876/5432-10</cnpj>
                    <cpf />
                    <endereco>AVENIDA COMERCIAL, 102</endereco>
                    <bairro>PRACA CENTRAL</bairro>
                    <cep>01234-567</cep>
                    <municipio>0000000 - AGUAS BRANCAS</municipio>
                    <telefone>(01)97531-2468</telefone>
                    <uf>AC</uf>
                    <pais>1058 - BRASIL</pais>
                    <indicador-ie>01 - Contribuinte ICMS</indicador-ie>
                    <ie>987654321</ie>
                    <suframa />
                    <im />
                    <email>comercial@objetos.com.br</email>
                    <normalizado-cnpj>32109876543210</normalizado-cnpj>
                    <normalizado-cpf />
                    <normalizado-cep>01234567</normalizado-cep>
                    <normalizado-municipio>0000000</normalizado-municipio>
                    <normalizado-pais>1058</normalizado-pais>
                    <normalizado-indicador-ie>1</normalizado-indicador-ie>
                    <municipio-icms>0101010</municipio-icms>
                    <cnae />
                </emitente>
                <info-adicionais>
                    <formato-impressao>1 - DANFE normal, retrato</formato-impressao>
                    <informacoes-complementares>PEDIDO: 123456</informacoes-complementares>
                    <normalizado-formato-impressao>1</normalizado-formato-impressao>
                    <compra>
                        <nota-empenho />
                        <pedido />
                        <contrato />
                    </compra>
                </info-adicionais>
                <local>
                    <cnpj />
                    <cpf />
                    <endereco />
                    <bairro />
                    <municipio />
                    <uf />
                    <normalizado-cnpj />
                    <normalizado-cpf />
                    <normalizado-municipio />
                </local>
                <nfe>
                    <modelo>12</modelo>345
                    <serie>344</serie>
                    <numero>909876</numero>
                    <data-emissao>01/12/2016 10:00:01-02:00</data-emissao>
                    <data-saida-entrada>02/12/2016 10:00:01-02:00</data-saida-entrada>
                    <valor-total>5.000,00</valor-total>
                    <normalizado-valor-total>5103.34</normalizado-valor-total>
                    <emitente>
                        <cnpj>32.109.876/5432-10</cnpj>
                        <nome>COMERCIO DE OBJETOS LTDA.</nome>
                        <ie>987654321</ie>
                        <uf>AC</uf>
                        <normalizado-cnpj>32109876543210</normalizado-cnpj>
                    </emitente>
                    <destinatario>
                        <cnpj>01.234.567/8901-23</cnpj>
                        <cpf />
                        <nome>EMPRESA FANTASIA LTDA.</nome>
                        <ie>123456789</ie>
                        <uf>AC</uf>
                        <destino-operacao>1 - Operação Interna</destino-operacao>
                        <consumidor-final>0 - Normal</consumidor-final>
                        <presenca-comprador>9 - Operação não presencial (outros)</presenca-comprador>
                        <normalizado-cnpj>01234567890123</normalizado-cnpj>
                        <normalizado-cpf />
                        <normalizado-destino-operacao>1</normalizado-destino-operacao>
                        <normalizado-consumidor-final>0</normalizado-consumidor-final>
                        <normalizado-presenca-comprador>9</normalizado-presenca-comprador>
                        <normalizado-pais>1058</normalizado-pais>
                    </destinatario>
                    <emissao>
                        <processo>0 - com aplicativo do Contribuinte</processo>
                        <versao>PROMOB_2_05</versao>
                        <tipo>1 - Normal</tipo>
                        <finalidade>1 - Normal</finalidade>
                        <natureza-operacao>VENDAS PROD. ESTABELECIMENTO (A PRAZO)</natureza-operacao>
                        <tipo-operacao>1 - Saída</tipo-operacao>
                        <forma-pagamento>1 - A prazo</forma-pagamento>
                        <digest>a840=vytMU-nrm4VE.EN9</digest>
                        <normalizado-processo>0</normalizado-processo>
                        <normalizado-tipo>1</normalizado-tipo>
                        <normalizado-finalidade>1</normalizado-finalidade>
                        <normalizado-tipo-operacao>1</normalizado-tipo-operacao>
                        <normalizado-forma-pagamento>1</normalizado-forma-pagamento>
                    </emissao>
                    <situacao>AUTORIZADA</situacao>
                    <situacao-ambiente>produção</situacao-ambiente>
                    <eventos>
                        <evento>
                            <evento>Autorização de Uso</evento>
                            <protocolo>01010101010</protocolo>
                            <data-autorizacao>01/12/2016 às 12:00:00-02:00</data-autorizacao>
                            <data-inclusao>25/01/2016 às 12:00:00</data-inclusao>
                        </evento>
                    </eventos>
                  </nfe>
                  <normalizado-chave-acesso>12345678909876543210123456789098765432101234</normalizado-chave-acesso>
                  <produtos>
                      <produto>
                          <num>1</num>
                          <descricao>PRODUTO CATALOGADO NA LOJA</descricao>
                          <qtd>1</qtd>
                          <unidade>UN</unidade>
                          <valor>10.000,10</valor>
                          <normalizado-valor>10000.1</normalizado-valor>
                          <codigo>01234-123</codigo>
                          <ncm>00012345</ncm>
                          <cest />
                          <ex-tipi />
                          <cfop />
                          <outras-despesas />
                          <valor-desconto />
                          <valor-frete />
                          <valor-seguro />
                          <composicao-valor>1 - O valor do item (vProd) compõe o valor total da NF-e (vProd)</composicao-valor>
                          <ean-comercial>012321123</ean-comercial>
                          <unidade-comercial>UN</unidade-comercial>
                          <quantidade-comercial>1,0000</quantidade-comercial>
                          <ean-tributavel>011010101</ean-tributavel>
                          <unidade-tributavel>UN</unidade-tributavel>
                          <quantidade-tributavel>1,0000</quantidade-tributavel>
                          <valor-unitario-comercial>10.000,1000000000</valor-unitario-comercial>
                          <valor-unitario-tributavel>10.000,1000000000</valor-unitario-tributavel>
                          <numero-pedido />
                          <item-pedido />
                          <tributos />
                          <fci />
                          <icms>
                              <origem-mercadoria>0 - Nacional</origem-mercadoria>
                              <tributacao-icms>00 - Tributada integralmente</tributacao-icms>
                              <modalidade />
                              <uf />
                          </icms>
                          <pis>
                              <cst>01 - Operação Tributável (base de cálculo = valor da operação alíquota normal (cumulativo/não cumulativo))</cst>
                              <base-calculo>0,00</base-calculo>
                              <aliquota>0,0000</aliquota>
                              <valor>0,00</valor>
                          </pis>
                          <cofins>
                              <cst>01 - Operação Tributável (base de cálculo = valor da operação alíquota normal (cumulativo/não cumulativo))</cst>
                              <base-calculo>0,00</base-calculo>
                              <aliquota>0,0000</aliquota>
                              <valor>0,00</valor>
                          </cofins>
                      </produto>
                  </produtos>
                  <totais>
                      <base-calculo-icms>0,00</base-calculo-icms>
                      <valor-icms>0,00</valor-icms>
                      <desonerado-icms>0,00</desonerado-icms>
                      <base-calculo-icms-st>0,00</base-calculo-icms-st>
                      <valor-icms-st>0,00</valor-icms-st>
                      <valor-produtos>10.000,10</valor-produtos>
                      <valor-frete>0,00</valor-frete>
                      <valor-seguro>0,00</valor-seguro>
                      <outras-despesas>0,00</outras-despesas>
                      <valor-ipi>0,00</valor-ipi>
                      <valor-nfe>0,00</valor-nfe>
                      <valor-descontos>0,00</valor-descontos>
                      <valor-ii>0,00</valor-ii>
                      <valor-pis>0,00</valor-pis>
                      <valor-cofins>0,00</valor-cofins>
                      <valor-tributos />
                      <valor-icms-fcp />
                      <valor-icms-interestadual-dest />
                      <valor-icms-interestadual-rem />
                      <normalizado-base-calculo-icms>0</normalizado-base-calculo-icms>
                      <normalizado-valor-icms>0</normalizado-valor-icms>
                      <normalizado-desonerado-icms>0</normalizado-desonerado-icms>
                      <normalizado-base-calculo-icms-st>0</normalizado-base-calculo-icms-st>
                      <normalizado-valor-icms-st>0</normalizado-valor-icms-st>
                      <normalizado-valor-produtos>10000.1</normalizado-valor-produtos>
                      <normalizado-valor-frete>0</normalizado-valor-frete>
                      <normalizado-valor-seguro>0</normalizado-valor-seguro>
                      <normalizado-outras-despesas>0</normalizado-outras-despesas>
                      <normalizado-valor-ipi>0</normalizado-valor-ipi>
                      <normalizado-valor-nfe>0</normalizado-valor-nfe>
                      <normalizado-valor-descontos>0</normalizado-valor-descontos>
                      <normalizado-valor-ii>0</normalizado-valor-ii>
                      <normalizado-valor-pis>0</normalizado-valor-pis>
                      <normalizado-valor-cofins>0</normalizado-valor-cofins>
                      <normalizado-valor-tributos>0</normalizado-valor-tributos>
                      <normalizado-valor-icms-fcp>0</normalizado-valor-icms-fcp>
                      <normalizado-valor-icms-interestadual-dest>0</normalizado-valor-icms-interestadual-dest>
                      <normalizado-valor-icms-interestadual-rem>0</normalizado-valor-icms-interestadual-rem>
                  </totais>
                  <transporte>
                      <modalidade-frete>1 - Por Conta do Destintário</modalidade-frete>
                      <normalizado-modalidade-frete>1</normalizado-modalidade-frete>
                      <transportador>
                          <cnpj>12.345.677/6543-21</cnpj>
                          <nome>TRANSPORTE DE RECURSOS EMPRESARIAIS</nome>
                          <ie>0192837465</ie>
                          <endereco />
                          <municipio>ALDEIA ROXA</municipio>
                          <uf>AC</uf>
                          <normalizado-cnpj>12345677654321</normalizado-cnpj>
                      </transportador>
                      <veiculo>
                          <placa>TRE0123</placa>
                          <uf>AC</uf>
                          <rntc />
                      </veiculo>
                  </transporte>
              </nfe>
            </response>

+ Response 404 (application/xml)

### Consulta de dados de cedente [GET /v1/nfe-validations/{nfe_validation_id}/seller]

+ Request

    + Headers

            Authorization: Bearer {token}

+ Parameters

    + nfe_validation_id - Identificador da validação de nota fiscal.

+ Response 200 (application/xml)

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <response>
              <code type="integer">200</code>
              <description>Sucesso</description>
              <participante>
                  <abertura-data>01/01/2001</abertura-data>
                  <atividade-economica>00.01-1-00 - Venda de equipamentos</atividade-economica>
                  <atividade-economica-secundaria>01.01-1-00 - Fabricação de equipamentos</atividade-economica-secundaria>
                  <atividade-economica-secundaria-lista>01.01-1-00 - Fabricação de equipamentos</atividade-economica-secundaria-lista>
                  <capital-social>R$ 1.000.000,00 (Um milhão de reais)</capital-social>
                  <cnpj>12.098.345/7654-67</cnpj>
                  <consulta-datahora>01/12/2016 16:00:00</consulta-datahora>
                  <efr>*****</efr>
                  <email></email>
                  <endereco-bairro>AREA COMERCIAL</endereco-bairro>
                  <endereco-cep>12.345-098</endereco-cep>
                  <endereco-complemento>CONJUNTO 1010</endereco-complemento>
                  <endereco-logradouro>CENTRAL DE RECURSOS</endereco-logradouro>
                  <endereco-municipio>VALE MINERAL</endereco-municipio>
                  <endereco-numero>39</endereco-numero>
                  <endereco-uf>AC</endereco-uf>
                  <matriz-filial>MATRIZ</matriz-filial>
                  <natureza-juridica>206-2 - SOCIEDADE EMPRESARIA LIMITADA</natureza-juridica>
                  <nome-fantasia>FABRICA BRASILEIRA</nome-fantasia>
                  <normalizado-abertura-data>01/01/2001</normalizado-abertura-data>
                  <normalizado-capital-social>1000000</normalizado-capital-social>
                  <normalizado-cnpj>12098345765467</normalizado-cnpj>
                  <normalizado-consulta-datahora>01/12/2016 16:00:00</normalizado-consulta-datahora>
                  <normalizado-endereco-cep>12345098</normalizado-endereco-cep>
                  <normalizado-situacao-cadastral-data>01/01/2005</normalizado-situacao-cadastral-data>
                  <normalizado-situacao-especial-data></normalizado-situacao-especial-data>
                  <qsa>
                      <socio>
                          <nome>JOAO BORGES</nome>
                          <qualificacao>49-Sócio-Administrador</qualificacao>
                      </socio>
                  </qsa>
                  <razao-social>INDUSTRIA E COMERCIO DE RECURSOS COMERCIAIS LTDA.</razao-social>
                  <situacao-cadastral>ATIVA</situacaoC-cdastral>
                  <situacao-cadastral-data>01/01/2005</situacao-cadastral-data>
                  <situacao-cadastral-observacoes></situacao-cadastral-observacoes>
                  <situacao-especial>********</situacao-especial>
                  <situacao-especial-data>********</situacao-especial-data>
                  <telefone>(01) 9283-74651</telefone>
              </participante>
            </response>

+ Response 404 (application/xml)

### Consulta de dados de sacado [GET /v1/nfe-validations/{nfe_validation_id}/buyer]

+ Request

    + Headers

            Authorization: Bearer {token}

+ Parameters

    + nfe_validation_id - Identificador da validação de nota fiscal.

+ Response 200 (application/xml)

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <response>
              <code type="integer">200</code>
              <description>Sucesso</description>
              <participante>
                  <abertura-data>01/01/2001</abertura-data>
                  <atividade-economica>00.01-1-00 - Venda de equipamentos</atividade-economica>
                  <atividade-economica-secundaria>01.01-1-00 - Fabricação de equipamentos</atividade-economica-secundaria>
                  <atividade-economica-secundaria-lista>01.01-1-00 - Fabricação de equipamentos</atividade-economica-secundaria-lista>
                  <capital-social>R$ 1.000.000,00 (Um milhão de reais)</capital-social>
                  <cnpj>12.098.345/7654-67</cnpj>
                  <consulta-datahora>01/12/2016 16:00:00</consulta-datahora>
                  <efr>*****</efr>
                  <email></email>
                  <endereco-bairro>AREA COMERCIAL</endereco-bairro>
                  <endereco-cep>12.345-098</endereco-cep>
                  <endereco-complemento>CONJUNTO 1010</endereco-complemento>
                  <endereco-logradouro>CENTRAL DE RECURSOS</endereco-logradouro>
                  <endereco-municipio>VALE MINERAL</endereco-municipio>
                  <endereco-numero>39</endereco-numero>
                  <endereco-uf>AC</endereco-uf>
                  <matriz-filial>MATRIZ</matriz-filial>
                  <natureza-juridica>206-2 - SOCIEDADE EMPRESARIA LIMITADA</natureza-juridica>
                  <nome-fantasia>FABRICA BRASILEIRA</nome-fantasia>
                  <normalizado-abertura-data>01/01/2001</normalizado-abertura-data>
                  <normalizado-capital-social>1000000</normalizado-capital-social>
                  <normalizado-cnpj>12098345765467</normalizado-cnpj>
                  <normalizado-consulta-datahora>01/12/2016 16:00:00</normalizado-consulta-datahora>
                  <normalizado-endereco-cep>12345098</normalizado-endereco-cep>
                  <normalizado-situacao-cadastral-data>01/01/2005</normalizado-situacao-cadastral-data>
                  <normalizado-situacao-especial-data></normalizado-situacao-especial-data>
                  <qsa>
                      <socio>
                          <nome>JOAO BORGES</nome>
                          <qualificacao>49-Sócio-Administrador</qualificacao>
                      </socio>
                  </qsa>
                  <razao-social>INDUSTRIA E COMERCIO DE RECURSOS COMERCIAIS LTDA.</razao-social>
                  <situacao-cadastral>ATIVA</situacaoC-cdastral>
                  <situacao-cadastral-data>01/01/2005</situacao-cadastral-data>
                  <situacao-cadastral-observacoes></situacao-cadastral-observacoes>
                  <situacao-especial>********</situacao-especial>
                  <situacao-especial-data>********</situacao-especial-data>
                  <telefone>(01) 9283-74651</telefone>
              </participante>
            </response>

+ Response 404 (application/xml)

### Consulta das constatações CERC [GET /v1/nfe-validations/{nfe_validation_id}/conclusions]

+ Request

    + Headers

            Authorization: Bearer {token}

+ Parameters

    + nfe_validation_id - Identificador da validação de nota fiscal.

+ Response 200 (application/xml)

    + Attributes(Response Base)

        + `conclusions` (array[NfeValidationConclusion]) - Lista de conslusões sobre a validação da nota fiscal.

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <response>
              <code type="integer">200</code>
              <description>Sucesso</description>
              <conclusions type="array">
                <conclusion>
                  <message>Dados estão coerentes</message>
                  <scope>dfe</scope>
                  <dimension>fiscal</dimension>
                  <algorithm>Algoritmo 1</algorithm>
                  <impact>positive</impact>
                  <nfe-key>1616 0172 3514 6459 2140 9595 6962 7754 2902 4102 8783</nfe-key>
                  <concluded-date type="time">2016-08-19T13:27:53-03:00</concluded-date>
                </conclusion>
                <conclusion>
                  <message>Dados estão incoerentes</message>
                  <scope>dfe</scope>
                  <dimension>fiscal</dimension>
                  <algorithm>Algoritmo 2</algorithm>
                  <impact>negative</impact>
                  <nfe-key>1616 0172 3514 6459 2140 9595 6962 7754 2902 4102 8783</nfe-key>
                  <concluded-date type="time">2016-08-19T13:27:53-03:00</concluded-date>
                </conclusion>
              </conclusions>
            </response>

+ Response 404 (application/xml)

## Registro definitivo de operação com duplicata mercantil [/v1/registro-definitivo-de-operacao-duplicata-mercantil]

Ao registrar uma operação na CERC, o Agente Registrador deve informar à CERC os dados dos recebíveis que um Agente Financiador pretenda adquirir ou vincular como garantia de uma operação de crédito.
Uma vez confirmado o registro pela CERC, os recebíveis estarão associados como lastro da operação do Agente Financiador indicado.
Realizando o registro da operação com recebíveis na CERC, o Agente Financiador evita que o mesmo recebível seja cedido ou vinculado a operação de outro Agente Financiador habilitado junto à CERC.
O Registro definitivo é um serviço que compreende o processo de validação de NFe como requisito. Assim, o registro não será realizado caso seja indicada uma chave de NF-e inválida, ou se identificada indisponibilidade do recebível ou inconsistências no documento fiscal associado.

### Registro definitivo de operações com duplicata mercantil [POST]

Aplicável ao Agente de Registro e pendente de especificação.

### Status de registro definitivo de operações com duplicata mercantil [GET /v1/registro-definitivo-de-operacao-com-duplicata-mercantil/status]

Aplicável ao Agente de Registro e pendente de especificação.

### Consulta de registro definitivo de operações com duplicata mercantil [GET /v1/registro-definitivo-de-operacao-duplicata-mercantil]

Pendente de especificação. Este serviço fornece os dados dos registros definitivos das operações com recebíveis realizadas pelo Agente Financiador.

## Registro provisório de operação com duplicata mercantil [/v1/registro-provisorio-de-operacao-duplicata-mercantil]

O Registro provisório de operação com duplicata mercantil deve ser utilizado nos casos em que o Agente Financiador decide adquirir ou vincular como garantia um recebível de que não dispõe dos dados do documento fiscal correspondente.
O registro provisório tem caráter transitório e não compreende a validação de documento fiscal. Serve somente para garantir a unicidade da propriedade (definitiva ou fiduciária) de um recebível, e deve ser posteriormente objeto de associação deste registro com um documento fiscal válido, para que se converta em um registro definitivo.

### Registro provisório de operações com duplicata mercantil [POST]

Aplicável ao Agente de Registro e pendente de especificação.

### Status de registro provisório de operações com duplicata mercantil  [GET /v1/registro-provisorio-de-operacao-duplicata-mercantil/status]

Aplicável ao Agente de Registro e pendente de especificação.

### Consulta de registros provisórios de operações com duplicata mercantil [GET /v1/registro-provisorio-de-operacao-duplicata-mercantil]

Pendente de especificação. Este serviço fornece os dados dos registros provisórios das operações com recebíveis realizadas pelo Agente Financiador.

## Associação de registro provisório de operação a NF-e [/registro-provisorio-em-lote/promover]

A conversão de registro provisório de operação com duplicata mercantil em um registro definitivo ocorre por meio da indicação do documento fiscal associado ao recebível objeto do registro.
O serviço realiza a associação de um ou mais recebíveis que possuam registros provisórios a uma ou mais NF-e.

### Solicitação de atualização de registros provisórios em lote [POST]

Pendente de especificação.

### Consulta da solicitação de atualização de registros provisórios em lote [GET /registro-provisorio-em-lote/{protocolo}]

Pendente de especificação.

## Acompanhamento da carteira

O conjunto de serviços de acompanhamento da carteira oferece como resultado os dados de monitoramento dos recebíveis registrados e ativos de um Agente Financiador.
O monitoramento compreende as alterações nos documentos fiscais ocorridas a partir dos eventos a estes associados, bem como as mudanças nos dados dos participantes do recebível (emitente/cedente e devedor/sacado) constatadas a partir das consultas recorrentes as fontes de dados utilizadas pela CERC.


### Consulta de novos dados das NF-e objeto de registro

Pendente de especificação.

### Consulta de novos dados dos participantes objeto de registro

Pendente de especificação.

# Data Structures

## Response Base (object)

+ code (number) - O código correspondente ao retorno.

+ description (string) - A descrição do código.


## Agent User (object)

+ name (string) - Identificador do usuário de agente.

+ email (string) - Email do usuário de agente.

+ `telephone-number` (string) - Telefone do usuário de agente. Vem com máscara no formato: `(XX) XXXXX-XXXX`

## NfeValidation (object)

+ id (string) - Identificador da validação de nota fiscal.

+ status (enum[string])
    Status atual da validação de nota fiscal.
    Pode ter um dos seguintes valores:
    + Members
        + `pendente` - Pendente de processamento e obtenção de dados.
        + `processando` - Obtenção de dados e processamento em andamento.
        + `concluido` - Validação concluída.
        + `com_erro` - Validação com erro que impede o resultado.

+ `agent-id` (string) - Identificador do agente associado a validação.

+ `created-date` (string) - Data no formato iso8601 em que a soliticação da validação foi criada. Ou seja, data de solicitação da validação em lote a que essa validação está associada.

+ `concluded-date` (string) - Data no formato iso8601 em que a validação de nota fiscal foi concluída.

+ `batch-id` (string) - Identificador do lote de validação de nota fiscal ao qual essa validação pertence.

## NfeValidationConclusion (object)

+ message (string) - Mensagem da conclusão.

+ scope (enum[string])
    Escopo da conclusão.
    Pode ter um dos seguintes valores:
    + Members
        + `dfe` - Documento fiscal.
        + `participant` - Participante.
        + `recebivel` - Recebível.

+ dimension (enum[string])
    Dimensão da conclusão.
    Pode ter um dos seguintes valores:
    + Members
        + `credit` - Crédito.
        + `fiscal` - Fiscal.
        + `logistic` - Logística.
        + `mercantile` - Mercantil.

+ algorithm (string) - Algoritmo utilizado na conclusão.

+ impact (enum[string])
    Impacto resultante da conclusão.
    Pode ter um dos seguintes valores:
    + Members
        + `negative` - Negativo.
        + `neutral` - Neutro.
        + `positive` - Positivo.

+ `nfe-key` (string) - Chave da nota referente a conclusão.

+ `concluded-date` (string) - Data no formato iso8601 em que a conclusão foi gerada.
