FORMAT: 1A
HOST: http://cerc-api-staging.herokuapp.com/

# CERC API

This is a sample text that must be replaced to an introduction to the api.

## Registro de Recebíveis [/v1/nfe/recebiveis/registers]

Este endpoint só trabalhará com duplicatas de NFe.

### Listar recebíveis registrados [GET]

Lista todos os recebíveis registrados.

+ Response 200 (application/json)

        [
            {
                id: "57b2285b5192b47bb6c5272b",
                agent_id: "57b2285b5192b47bb6c5272c",
                drawee_id: "57b2285b5192b47bb6c5272d",
                transferor_id: "57b2285b5192b47bb6c5272e",
                value_in_cents: 123131,
                recebivel_id: "57b2285b5192b47bb6c5272f",
                due_date: "12/03/2016",
                nfe_key: "231321421421421412412421",
                document_number: "1000-A",
            },
            {
                id: "58b2285b5192b47bb6c5272b",
                agent_id: "58b2285b5192b47bb6c5272c",
                drawee_id: "58b2285b5192b47bb6c5272d",
                transferor_id: "58b2285b5192b47bb6c5272e",
                value_in_cents: 123131,
                recebivel_id: "58b2285b5192b47bb6c5272f",
                due_date: "12/04/2016",
                nfe_key: "231321421421421412412421",
                document_number: "1000-B",
            }
        ]

### Solicitar registro definitivo de recebíveis [POST]

Recebe um conjunto de duplicatas (chave da NFe, id da duplicata, valor da duplicata, data de vencimento)
e as registra em nome de um agente.

+ Request (application/json)

        {
            "agent_id": "58b2285b5192b47bb6c5272c",
            "recebiveis": [
                {
                    "nfe_key": "231321421421421412412421",
                    "duplicates": [
                        {
                            "document_number": "1000-A",
                            "value_in_cents": 21313213,
                            "due_date": "12/11/2016"
                        },
                        {
                            "document_number": "1000-B",
                            "value_in_cents": 21313213,
                            "due_date": "12/12/2016"
                        }
                    ]
                }
            ]
        }

+ Response 202 (application/json)

    + Body

            {
                protocol: 1231321313131,
                message: "O lote foi aceito e será processado",
            }

+ Request (application/json)

        {
            "agent_id": "58b2285b5192b47bb6c5272c",
            "recebiveis": [
                {
                    "nfe_key": "231321421421421412412421",
                    "duplicates": [
                        {
                            "document_number": "1000-A",
                            "value_in_cents": 21313213,
                            "due_date": "12/11/2016"
                        },
                        {
                            "document_number": "1000-B",
                            "value_in_cents": 21313213,
                            "due_date": "12/12/2016"
                        }
                }
            ]
        }

+ Response 422 (application/json)

    + Body

            {
                error_message: "Formato inválido.",
                error_code: 1
            }

+ Request (application/json)

        {
            "agent_id": "1",
            "recebiveis": [
                {
                    "nfe_key": "231321421421421412412421",
                    "duplicates": [
                        {
                            "document_number": "1000-A",
                            "value_in_cents": 21313213,
                            "due_date": "12/11/2016"
                        },
                        {
                            "document_number": "1000-B",
                            "value_in_cents": 21313213,
                            "due_date": "12/12/2016"
                        }
                    ]
                }
            ]
        }

+ Response 422 (application/json)

    + Body

            {
                error_message: "O agente fornecido não existe.",
                error_code: 2
            }


## Status da Solicitação de registro definitivo [/v1/nfe/recebiveis/{protocol}/status]

Endpoint para realizar pulling das informações relacionadas a um lote de
recebíveis em processo de registro.

### Ver status [GET]

Retorna o status do processo de registro de cada recebivel no lote enviado.

+ Parameters
    + protocol (number) - o número do protocolo fornecido na solicitação de registro

+ Response 200 (application/json)


    + Body

            {
                protocol: 1312321,
                lote_status_code: 003,
                status_message: "Em processamento",
                processamento_de_recebiveis: [
                    {
                        nfe_key: "123123123213",
                        document_number: "1000-A",
                        status_code: 123,
                        register_id: "57b2285b5192b47bb6c5272d"

                    },
                    {
                        nfe_key: "123123123213",
                        document_number: "1000-B",
                        status_code: 124,
                        register_id: "57b2285b5192b47bb6c5272e"

                    }
                ]
            }


## Nested section [/bla/sayhi]

This is a sample nested section

### Sample nested request [POST]

+ Request (application/json)

        {
            "message": "Hello my friend"
        }


+ Response 201 (application/json)

    + Body

            {
            }
